apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: slack-content-gateway
  app.kubernetes.io/part-of: content-safety

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - slack-secret-sealed.yaml
  - openai-secret-sealed.yaml

images:
  - name: lucashvieira/slack-content-gateway
    newTag: 0.2.0
